### ISSUE TITLE
Error Handling no network connection

### ISSUE THREAD

**Issue by shivam043** [shivam043/instantnews#2]

**Comment by ghost-hacked** [comment]
Mind if I take a look at this?

**Comment by shivam043** [comment]
sure @connorkendrick

**Comment by ghost-hacked** [comment]
Would you mind if I cleaned up the line spacing and Pydoc function comments while I'm at it? I can leave it alone or do it in another PR if you want.

**Comment by ghost-hacked** [comment]
Never mind, I'll leave that to another PR.
